name: Trigger auto deployment for action-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/ActionTestApp/**'
    - '.github/workflows/action-test-app-AutoDeployTrigger-0c6a7ecf-d6e6-4e10-afff-88b80c49ed5d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: iyulabimages.azurecr.io
          username: ${{ secrets.ACTIONTESTAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.ACTIONTESTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iyulabimages.azurecr.io/actiontestapp:${{ github.sha }}
          file: ./src/ActionTestApp/Dockerfile
          context: ./src/ActionTestApp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACTIONTESTAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n action-test-app -g iyulab-rnd --server iyulabimages.azurecr.io --username  ${{ secrets.ACTIONTESTAPP_REGISTRY_USERNAME }} --password ${{ secrets.ACTIONTESTAPP_REGISTRY_PASSWORD }}
            az containerapp update -n action-test-app -g iyulab-rnd --image iyulabimages.azurecr.io/actiontestapp:${{ github.sha }}
